opcion= int(input("Seleccione una opcion:  \n 1.- Configurar una interfaz. \n 2.- Configurar una interfaz y crear en OSPF." ))
if opcion == 1:
    interface= ("ingrese la interfaz: ")
    ip=("ingrese la ip: ")
    mascara=("ingrese la mascara: ")
    nombre= ("ingrese el nombre: ")
    print("interface g0/ ", interface)
    print("no shut")
    print("ip address ", ip, " ", mascara)
    print( "Description ***", nombre)
    print ("speed 100")
    print("Duplex full")
    print("Consulte con los siguientes comandos:")
    print("Show ip interface brief")
    print("Show run interface g0/")
    print("Show interface g0/")
else:
    
    interface= ("ingrese la interfaz: ")
    mascara=("ingrese la mascara: ")
    ip=("ingrese la ip: ")
    ipred=("ingrese la ip de red: ")
    wildcard=("ingrese la wildcar: ")
    NumeroOSPF= ("ingrese el numero de proceso: ")
    ID_OSPF= ("Ingrese el ID del area OSPF: ")
    routerID= ("ingrese el ID de router: ")
    print("router ospf ", NumeroOSPF)
    print("router-id ", routerID)
    print("network ", ipred, wildcard, "area ", ID_OSPF)
    print("interface ", interface)
    print("ip address ", ip, mascara)
    print("consulte con los siguientes comandos: ")
    print("Show ip ospf neighbour")
    

